# NumPy
### Linear Algebra library for Python 
1D vector or 2D arrays

In [5]:
mylist = [1,2,3]
import numpy as np
arr = np.array(mylist)
arr

array([1, 2, 3])

In [7]:
# Matrix
mymat = [[1,2,3],[4,5,6],[7,8,9]]
np.array(mymat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
# start at 0 and give 10 elements
# Similar to Python range function
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
# Can specify step size as well
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [13]:
np.zeros(3)

array([0., 0., 0.])

In [20]:
# tuple of dimentions is passed as a parameter for a matrix
np.zeros((5,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [21]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [27]:
# linspace returns linearly spaced values 
# 3rd argument gives number of points
# dont confuse with arange which takes step size as 3rd argument
np.linspace(0,5,11)

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. ])

In [28]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [33]:
# Uniformly distributed values between 0 and 1
# Here we are no passing in tuple as dimentions
# We just directly pass the dimentions
np.random.rand(2,3)

array([[0.38291952, 0.35305325, 0.49243906],
       [0.61859572, 0.26736073, 0.37796282]])

In [35]:
# For Gaussian Distribution centered around 0
np.random.randn(2,3)

array([[ 0.38209981,  1.07865532,  1.15535173],
       [ 0.51346954, -0.04879807, -0.00510782]])

In [36]:
# random integers
# lower limit is inclusive; upper limit is non inclusive
# 3rd argument is optional - gives the number of integers you want
np.random.randint(10, 100, 4)

array([18, 58, 82, 67])

In [37]:
arr = np.arange(25)
ranarr = np.random.randint(0,50,10)

In [41]:
# Reshape - for reshaping matrix to a different dimention
# Similar to Octave/Matlab
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [49]:
# Max and Min values and locations
maximum = ranarr.max()
minimum = ranarr.min()
maxindex = ranarr.argmax()
minindex = ranarr.argmin()
print (" Random Array = {}, with max value {} at index {} and min value {} at index {}".format(ranarr,maximum,maxindex,minimum,minindex))

 Random Array = [33  6  4 18  0 47 47  4 30  9], with max value 47 at index 5 and min value 0 at index 4


In [51]:
# Get the shape of the array
# Note no paranthesis arounf shape
arr.shape

(25,)

In [53]:
# Returns data types in the array
arr.dtype

dtype('int32')

### Indexing and Selection for NumPy

In [54]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [62]:
arr[5]

5

In [56]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [58]:
# Same a Python List
# Starting index is inclusive; Ending index is not inclusive
arr[5:7]

array([5, 6])

In [61]:
# Starting at index 0 and ending not inclusive of index 5
arr[:5]

array([0, 1, 2, 3, 4])

In [63]:
# NumPy arrays difer from lists in their ability to broadcast
arr[0:5] =  100
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [67]:
# By degault when you assign one array (or slice) to another,
# Python creates a reference to that array (or slice)
# This is done to avoid memory issues with large arrays
# If you want to create a copy, you have to do this explicitly

In [68]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [69]:
slice_arr = arr[0:6]
slice_arr

array([0, 1, 2, 3, 4, 5])

In [72]:
slice_arr[:] = 100
slice_arr

array([100, 100, 100, 100, 100, 100])

In [73]:
arr


array([100, 100, 100, 100, 100, 100,   6,   7,   8,   9,  10])

In [74]:
# Note how the original array has also been changed

In [76]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [79]:
slice_arr = arr.copy()
slice_arr[:] = 100
slice_arr

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [80]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [81]:
# Note that in this case, the original array is not affected

In [85]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [89]:
# Double bracket notation
arr_2d[1][2]

30

In [92]:
# Preferred Method: Single Bracket indexing
arr_2d[1,2]

30

In [91]:
arr_2d[1]

array([20, 25, 30])

In [100]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [104]:
# Sliced notation to grab subset of this matrix
# Remember 1: includes index 1; :2 does not include 2
arr_2d[1:,:2]

array([[20, 25],
       [35, 40]])

In [105]:
arr_2d[1:,:]

array([[20, 25, 30],
       [35, 40, 45]])

** Conditional Selection **

In [107]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [110]:
bool_array = arr > 5
bool_array

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [111]:
# Similar to Filter Function
arr[bool_array]

array([ 6,  7,  8,  9, 10])

In [112]:
# Comnbinig above into 1 statement
# this is more compact and used more often
# especially when using Pandas
arr[arr>5]

array([ 6,  7,  8,  9, 10])

In [123]:
# Practice problem
arr_2d = np.arange(50).reshape(5,10)
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [124]:
# grab values 13,14; 23,24
arr_2d[1:3,3:5]

array([[13, 14],
       [23, 24]])

### NymPy Operartions

In [128]:
# element wise operations
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [129]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [130]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [131]:
arr * arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [132]:
arr * 5

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [134]:
# sometimes we get a warnign instead of an error
# example below when we try to divide by 0
arr/arr

C:\Users\salma\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: RuntimeWarning: invalid value encountered in true_divide
  This is separate from the ipykernel package so we can avoid doing imports until


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [135]:
# Here also you get a warning but you get inf instead of nan
1/arr

C:\Users\salma\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])

In [142]:
# Lot of build in mathematical functions are available
# Universal array functions
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [137]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [138]:
np.max(arr)

10

In [140]:
# Above is same as following
arr.max()

10

In [141]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [144]:
np.power(arr,2)

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

# End of NumPy Notes